In [1]:
import os
import psycopg
import dotenv
import pandas as pd

connection = {"sslmode": "require", "target_session_attrs": "read-write"}
dotenv.load_dotenv()
postgres_credentials = {
    "host": os.getenv("DB_DESTINATION_HOST"),
    "port": os.getenv("DB_DESTINATION_PORT"),
    "dbname": os.getenv("DB_DESTINATION_NAME"),
    "user": os.getenv("DB_DESTINATION_USER"),
    "password": os.getenv("DB_DESTINATION_PASSWORD"),
}
assert all([var_value != "" for var_value in list(postgres_credentials.values())])

connection.update(postgres_credentials)
TABLE_NAME = "clean_flats_price"


with psycopg.connect(**connection) as conn:
    with conn.cursor() as cur:
        cur.execute(f"SELECT * FROM {TABLE_NAME}")
        data = cur.fetchall()
        columns = [col[0] for col in cur.description]


df = pd.DataFrame(data, columns=columns)

Добавляем отобранные на предудыщем этапе признаки

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import pandas as pd
from autofeat import AutoFeatRegressor
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing  import OneHotEncoder
from sklearn.preprocessing import RobustScaler
import mlflow
import numpy as np

CENTER_LAT = 55.7520
CENTER_LON = 37.6175

dotenv.load_dotenv()
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_registry_uri("http://127.0.0.1:5000")

df = df[df['ceiling_height'] != 27]

def haversine_distance(lat, lon):
    R = 6371  

    lat = np.radians(lat)
    lon = np.radians(lon)
    center_lat = np.radians(CENTER_LAT)
    center_lon = np.radians(CENTER_LON)

    dlat = lat - center_lat
    dlon = lon - center_lon

    a = np.sin(dlat / 2) ** 2 + np.cos(center_lat)* np.cos(lat) * np.sin(dlon / 2) ** 2
    

    return 2 * R * np.arcsin(np.sqrt(a))

df_copy = df.copy()
df_copy["distance_to_center"] = haversine_distance(
    df["latitude"],
    df["longitude"],
)

X = df_copy.drop(columns = ['price', 'building_id', 'studio'])
y = df_copy['price']

cat_features = df.select_dtypes(['object']).columns.tolist()
cat_features.append("building_type_int")
train_size = 0.8
shuffle=True

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=train_size, random_state=42, shuffle=shuffle)

autofeat_cols = [
    "total_area",
    "living_area",
    "kitchen_area",
    "rooms",
    "floor",
    "floors_total",
    "flats_count",
    "ceiling_height",
]
transformations = ["1/", "log",  "sqrt"]

auto = AutoFeatRegressor(
    feateng_steps=2,
    transformations=transformations,
    max_gb=10,
    feateng_cols=autofeat_cols
)
X_train_fe = auto.fit_transform(X_train, y_train)
X_test_fe = auto.transform(X_test)

rob_feat = [
    "kitchen_area",
    "living_area",
    "total_area",
    "ceiling_height",
]

selected_features = [
    "kitchen_area",
    "total_area",
    "ceiling_height",
    "building_type_int_2.0",
    "building_type_int_4.0",
    "building_type_int_5.0",
    "building_type_int_6.0",
    "id",
    "build_year",
    "latitude",
    "longitude",
    "has_elevator",
    "distance_to_center",
    "floor*floors_total",
    "floors_total*total_area",
    "kitchen_area*log(rooms)",
    "log(rooms)/floors_total",
    "flats_count*floors_total",
    "log(total_area)/ceiling_height",
    "ceiling_height*log(total_area)"
]

preprocessor = ColumnTransformer(
    [
        ("robust_scaler", RobustScaler(quantile_range=(10, 90)), rob_feat),
        ("categorical", OneHotEncoder(drop="if_binary", handle_unknown="ignore", sparse_output=False), cat_features)
    ],
    remainder="passthrough",
    verbose_feature_names_out=False,
)
preprocessor.set_output(transform="pandas")


X_train_transformed = preprocessor.fit_transform(X_train_fe, y_train,)

X_test_transformed = preprocessor.transform(X_test_fe)
X_train = X_train_transformed[selected_features]
X_test = X_test_transformed[selected_features]

Для подбора гиперпараметров будем использовать библиотеку optuna. Сначала протеристируем sampler TPE

In [10]:
from xgboost import XGBRegressor
import optuna
from optuna.integration.mlflow import MLflowCallback


EXPERIMENT_NAME = "flats_price"
RUN_NAME="hypeparams"
STUDY_DB_NAME = 'sqlite:///local.study.db'
STUDY_NAME = 'TPE'
TRACKING_SERVER_HOST = "localhost"
TRACKING_SERVER_PORT = 5000
def objective(trial):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 100, 1000),
        "max_depth": trial.suggest_int("max_depth", 3, 12),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
        "subsample": trial.suggest_float("subsample", 0.6, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0)
    }
    model = XGBRegressor(**params, objective="reg:squarederror",  eval_metric="rmse", random_state=42, n_jobs=-1)
    model.fit(X_train, y_train)
    pred = model.predict(X_test)

    rmse = np.sqrt(mean_squared_error(y_test, pred))
    return rmse

experiment_id = mlflow.get_experiment_by_name(EXPERIMENT_NAME).experiment_id

with mlflow.start_run(run_name=RUN_NAME, experiment_id=experiment_id) as run:
    run_id = run.info.run_id

    mlflc = MLflowCallback(tracking_uri=f'http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}',
                           metric_name="rmse", create_experiment=False,
                           mlflow_kwargs={'experiment_id': experiment_id, 'tags': {'mlflow.parentRunId': run_id}})

study = optuna.create_study(direction='minimize', study_name=STUDY_NAME,
                                 storage=STUDY_DB_NAME, load_if_exists=True, sampler=optuna.samplers.TPESampler())
study.optimize(objective, n_trials=10, callbacks=[mlflc])
best_params = study.best_params

print(f"Number of finished trials: {len(study.trials)}")
print(f"Best params: {best_params}")

/tmp/ipykernel_1772/3604417512.py:33: ExperimentalWarning: MLflowCallback is experimental (supported from v1.4.0). The interface can change in the future.
  mlflc = MLflowCallback(tracking_uri=f'http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}',
[I 2026-08-18 21:32:47,875] A new study created in RDB with name: TPE
[I 2026-08-18 21:32:59,278] Trial 0 finished with value: 2502804.70176238 and parameters: {'n_estimators': 349, 'max_depth': 12, 'learning_rate': 0.11384177128291817, 'min_child_weight': 9, 'subsample': 0.9183049482476509, 'colsample_bytree': 0.7164496789741365}. Best is trial 0 with value: 2502804.70176238.
[I 2026-08-18 21:33:05,330] Trial 1 finished with value: 2610985.2476636805 and parameters: {'n_estimators': 452, 'max_depth': 7, 'learning_rate': 0.023634970799338715, 'min_child_weight': 7, 'subsample': 0.9093116570307946, 'colsample_bytree': 0.7957710196949129}. Best is trial 0 with value: 2502804.70176238.
[I 2026-08-18 21:33:36,467] Trial 2 finished with value: 2531516.2302634493 and parameters: {'n_estimators': 878, 'max_depth': 12, 'learning_rate': 0.13993061043802718, 'min_child_weight': 6, 'subsample': 0.8876575673417122, 'colsample_bytree': 0.6855183794425621}. Best is trial 0 with value: 2502804.70176238.
[I 2026-08-18 21:33:54,769] Trial 3 finished with value: 2478012.2717515645 and parameters: {'n_estimators': 555, 'max_depth': 11, 'learning_rate': 0.056748192505557404, 'min_child_weight': 8, 'subsample': 0.9249292246860612, 'colsample_bytree': 0.9575984585294046}. Best is trial 3 with value: 2478012.2717515645.
[I 2026-08-18 21:34:06,087] Trial 4 finished with value: 2476446.749035992 and parameters: {'n_estimators': 703, 'max_depth': 8, 'learning_rate': 0.07530690221299437, 'min_child_weight': 5, 'subsample': 0.8218610503606728, 'colsample_bytree': 0.9841707155447389}. Best is trial 4 with value: 2476446.749035992.
[I 2026-08-18 21:34:09,985] Trial 5 finished with value: 2649462.000544121 and parameters: {'n_estimators': 442, 'max_depth': 5, 'learning_rate': 0.0521755900815875, 'min_child_weight': 8, 'subsample': 0.6870337147127425, 'colsample_bytree': 0.8943874921004855}. Best is trial 4 with value: 2476446.749035992.
[I 2026-08-18 21:34:23,186] Trial 6 finished with value: 2486834.025230005 and parameters: {'n_estimators': 889, 'max_depth': 7, 'learning_rate': 0.08316426560150324, 'min_child_weight': 2, 'subsample': 0.6436547027977148, 'colsample_bytree': 0.9191535574925012}. Best is trial 4 with value: 2476446.749035992.
[I 2026-08-18 21:34:31,292] Trial 7 finished with value: 2538927.076546317 and parameters: {'n_estimators': 541, 'max_depth': 8, 'learning_rate': 0.026702825518611632, 'min_child_weight': 10, 'subsample': 0.7916795671528396, 'colsample_bytree': 0.7986054257264562}. Best is trial 4 with value: 2476446.749035992.
[I 2026-08-18 21:34:34,268] Trial 8 finished with value: 2649342.275384401 and parameters: {'n_estimators': 258, 'max_depth': 6, 'learning_rate': 0.05214239674889534, 'min_child_weight': 2, 'subsample': 0.9097483348837495, 'colsample_bytree': 0.8778643163145943}. Best is trial 4 with value: 2476446.749035992.
[I 2026-08-18 21:34:39,116] Trial 9 finished with value: 2557671.615299766 and parameters: {'n_estimators': 642, 'max_depth': 5, 'learning_rate': 0.17152571227507585, 'min_child_weight': 10, 'subsample': 0.7771344092103305, 'colsample_bytree': 0.8392817185399197}. Best is trial 4 with value: 2476446.749035992.

Number of finished trials: 10
Best params: {'n_estimators': 703, 'max_depth': 8, 'learning_rate': 0.07530690221299437, 'min_child_weight': 5, 'subsample': 0.8218610503606728, 'colsample_bytree': 0.9841707155447389}

In [16]:
study.best_value

2476446.749035992

In [14]:
fig = optuna.visualization.plot_param_importances(study)
fig.write_image("hp_assets/tpe_param_importances.png")
fig.show()

Самые выжные параметры с отрывом можно видеть это learning_rate, n_estimators, max_depth

In [15]:
fig = optuna.visualization.plot_timeline(study)
fig.show()

/tmp/ipykernel_1772/2489585031.py:1: ExperimentalWarning:

plot_timeline is experimental (supported from v3.2.0). The interface can change in the future.

Самая лучшая модель по качеству оказалась второй худшей моделей по производительности.

Теперь проверим семпер

In [18]:
RUN_NAME = 'RandomSampler'
STUDY_NAME = "RandomSampler"
def objective(trial):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 100, 1000),
        "max_depth": trial.suggest_int("max_depth", 3, 12),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
        "subsample": trial.suggest_float("subsample", 0.6, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0)
    }
    model = XGBRegressor(**params, objective="reg:squarederror",  eval_metric="rmse", random_state=42, n_jobs=-1)
    model.fit(X_train, y_train)
    pred = model.predict(X_test)

    rmse = np.sqrt(mean_squared_error(y_test, pred))
    return rmse

experiment_id = mlflow.get_experiment_by_name(EXPERIMENT_NAME).experiment_id

with mlflow.start_run(run_name=RUN_NAME, experiment_id=experiment_id) as run:
    run_id = run.info.run_id

    mlflc = MLflowCallback(tracking_uri=f'http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}',
                           metric_name="rmse", create_experiment=False,
                           mlflow_kwargs={'experiment_id': experiment_id, 'tags': {'mlflow.parentRunId': run_id}})
study_2 = optuna.create_study(direction='minimize', study_name=STUDY_NAME,
                                 storage=STUDY_DB_NAME, load_if_exists=True, sampler=optuna.samplers.RandomSampler(seed=42))
study_2.optimize(objective, n_trials=10, callbacks=[mlflc])
best_params = study.best_params

print(f"Best_value: {study_2.best_value}")
print(f"Best params: {best_params}")

/tmp/ipykernel_1772/293665242.py:24: ExperimentalWarning:

MLflowCallback is experimental (supported from v1.4.0). The interface can change in the future.

[I 2026-08-18 21:46:44,646] A new study created in RDB with name: RandomSampler
[I 2026-08-18 21:48:38,437] Trial 0 finished with value: 2542885.582418505 and parameters: {'n_estimators': 437, 'max_depth': 12, 'learning_rate': 0.1205712628744377, 'min_child_weight': 6, 'subsample': 0.6624074561769746, 'colsample_bytree': 0.662397808134481}. Best is trial 0 with value: 2542885.582418505.
[I 2026-08-18 21:49:14,824] Trial 1 finished with value: 2543628.446541905 and parameters: {'n_estimators': 152, 'max_depth': 11, 'learning_rate': 0.07725378389307355, 'min_child_weight': 8, 'subsample': 0.608233797718321, 'colsample_bytree': 0.9879639408647978}. Best is trial 0 with value: 2542885.582418505.
[I 2026-08-18 21:50:17,438] Trial 2 finished with value: 2693310.468912077 and parameters: {'n_estimators': 850, 'max_depth': 5, 'learning_rate': 0.01855998084649059, 'min_child_weight': 2, 'subsample': 0.7216968971838151, 'colsample_bytree': 0.8099025726528951}. Best is trial 0 with value: 2542885.582418505.
[I 2026-08-18 21:50:50,163] Trial 3 finished with value: 2600886.874319927 and parameters: {'n_estimators': 489, 'max_depth': 5, 'learning_rate': 0.08012737503998542, 'min_child_weight': 2, 'subsample': 0.7168578594140873, 'colsample_bytree': 0.7465447373174767}. Best is trial 0 with value: 2542885.582418505.
[I 2026-08-18 21:52:37,658] Trial 4 finished with value: 2495286.409961169 and parameters: {'n_estimators': 510, 'max_depth': 10, 'learning_rate': 0.019721610970574007, 'min_child_weight': 6, 'subsample': 0.836965827544817, 'colsample_bytree': 0.6185801650879991}. Best is trial 4 with value: 2495286.409961169.
[I 2026-08-18 21:53:23,496] Trial 5 finished with value: 2896577.466572123 and parameters: {'n_estimators': 647, 'max_depth': 4, 'learning_rate': 0.012476394272569451, 'min_child_weight': 10, 'subsample': 0.9862528132298237, 'colsample_bytree': 0.9233589392465844}. Best is trial 4 with value: 2495286.409961169.
[I 2026-08-18 21:53:43,208] Trial 6 finished with value: 2772108.0841389378 and parameters: {'n_estimators': 374, 'max_depth': 3, 'learning_rate': 0.1024932221692416, 'min_child_weight': 5, 'subsample': 0.6488152939379115, 'colsample_bytree': 0.798070764044508}. Best is trial 4 with value: 2495286.409961169.
[I 2026-08-18 21:54:34,557] Trial 7 finished with value: 2662411.059012467 and parameters: {'n_estimators': 130, 'max_depth': 12, 'learning_rate': 0.024112898115291985, 'min_child_weight': 7, 'subsample': 0.7246844304357644, 'colsample_bytree': 0.8080272084711243}. Best is trial 4 with value: 2495286.409961169.
[I 2026-08-18 21:55:06,818] Trial 8 finished with value: 2574324.2658526343 and parameters: {'n_estimators': 592, 'max_depth': 4, 'learning_rate': 0.27051668818999286, 'min_child_weight': 8, 'subsample': 0.9757995766256756, 'colsample_bytree': 0.9579309401710595}. Best is trial 4 with value: 2495286.409961169.
[I 2026-08-18 21:59:02,365] Trial 9 finished with value: 2490403.850418112 and parameters: {'n_estimators': 638, 'max_depth': 12, 'learning_rate': 0.01351182947645082, 'min_child_weight': 2, 'subsample': 0.6180909155642152, 'colsample_bytree': 0.7301321323053057}. Best is trial 9 with value: 2490403.850418112.

Best_value: 2490403.850418112
Best params: {'n_estimators': 703, 'max_depth': 8, 'learning_rate': 0.07530690221299437, 'min_child_weight': 5, 'subsample': 0.8218610503606728, 'colsample_bytree': 0.9841707155447389}

In [20]:
model = XGBRegressor(n_estimators=703, learning_rate=0.07530690221299437, max_depth=8, min_child_weight=8, subsample=0.8218610503606728,
        colsample_bytree=0.9841707155447389, objective="reg:squarederror", eval_metric="rmse", random_state=42, n_jobs=-1)
model.fit(X_train, y_train)
pred = model.predict(X_test)

errors = pd.DataFrame({
    "y_true": y_test,
    "y_pred": pred
})

errors["error"] = errors["y_true"] - errors["y_pred"]
errors["abs_error"] = np.abs(errors["error"])
errors["squared_error"] = errors["error"] ** 2
errors.sort_values("squared_error", ascending=False).head(20)

            y_true      y_pred       error   abs_error  squared_error
94394     150000.0  36046756.0 -35896756.0  35896756.0   1.288577e+15
71359      70000.0  22498772.0 -22428772.0  22428772.0   5.030498e+14
116089     70000.0  22145504.0 -22075504.0  22075504.0   4.873279e+14
104377  35550000.0  13889893.0  21660107.0  21660107.0   4.691602e+14
120148  39200000.0  18777560.0  20422440.0  20422440.0   4.170761e+14
4103    40000000.0  19918910.0  20081090.0  20081090.0   4.032502e+14
42038    3200000.0  21913996.0 -18713996.0  18713996.0   3.502136e+14
89371    3550000.0  22074338.0 -18524338.0  18524338.0   3.431511e+14
113152  39950000.0  21610724.0  18339276.0  18339276.0   3.363290e+14
36663   35000000.0  17065924.0  17934076.0  17934076.0   3.216311e+14
112509   7490000.0  25317408.0 -17827408.0  17827408.0   3.178165e+14
8231    35000000.0  17907078.0  17092922.0  17092922.0   2.921680e+14
115805  38800000.0  21903296.0  16896704.0  16896704.0   2.854986e+14
102957   2238000.0  18917952.0 -16679952.0  16679952.0   2.782208e+14
98155   39900000.0  23514966.0  16385034.0  16385034.0   2.684693e+14
44753   19900000.0  36272608.0 -16372608.0  16372608.0   2.680623e+14
40651   20000000.0  35915504.0 -15915504.0  15915504.0   2.533033e+14
93056   22000000.0  37856924.0 -15856924.0  15856924.0   2.514420e+14
59779   39000000.0  23467632.0  15532368.0  15532368.0   2.412545e+14
17976   32990000.0  17701588.0  15288412.0  15288412.0   2.337355e+14

In [21]:
worst = errors.nlargest(20, "squared_error")

# Добавляем исходные признаки квартир
worst_objects = df_copy.loc[worst.index].copy()

worst_objects["y_true"] = worst["y_true"]
worst_objects["y_pred"] = worst["y_pred"]
worst_objects["abs_error"] = worst["abs_error"]
worst_objects["squared_error"] = worst["squared_error"]

worst_objects

,id,building_id,floor,kitchen_area,living_area,rooms,is_apartment,studio,total_area,price,...,longitude,ceiling_height,flats_count,floors_total,has_elevator,distance_to_center,y_true,y_pred,abs_error,squared_error
94394,108011,17630,10,21.000000,71.000000,3,False,False,130.000000,150000.0,...,37.484936,3.00,245,19,True,11.365019,150000.0,36046756.0,35896756.0,1.288577e+15
71359,80619,8738,7,10.000000,42.000000,1,False,False,65.000000,70000.0,...,37.576366,2.80,311,9,True,2.849062,70000.0,22498772.0,22428772.0,5.030498e+14
116089,134345,1698,6,12.000000,43.000000,2,False,False,64.000000,70000.0,...,37.635395,3.00,161,13,True,4.044973,70000.0,22145504.0,22075504.0,4.873279e+14
104377,120713,2805,1,7.000000,40.000000,3,False,False,57.000000,35550000.0,...,37.564320,2.80,75,5,False,6.064321,35550000.0,13889893.0,21660107.0,4.691602e+14
120148,139307,24195,10,0.000000,0.000000,2,False,False,68.599998,39200000.0,...,37.564213,3.00,1630,44,True,3.935317,39200000.0,18777560.0,20422440.0,4.170761e+14
4103,4334,893,2,10.800000,80.000000,4,False,False,111.800003,40000000.0,...,37.470383,3.00,64,6,True,14.760670,40000000.0,19918910.0,20081090.0,4.032502e+14
42038,46050,663,4,8.000000,18.400000,3,False,False,85.000000,3200000.0,...,37.612156,3.00,80,5,False,3.963338,3200000.0,21913996.0,18713996.0,3.502136e+14
89371,102098,4209,6,11.000000,30.000000,2,False,False,54.000000,3550000.0,...,37.565971,3.00,130,8,True,3.667449,3550000.0,22074338.0,18524338.0,3.431511e+14
113152,131002,18799,13,18.799999,41.200001,2,False,False,79.400002,39950000.0,...,37.803234,3.00,147,18,True,12.662986,39950000.0,21610724.0,18339276.0,3.363290e+14
36663,40061,14053,20,13.000000,0.000000,3,False,False,80.000000,35000000.0,...,37.540874,2.64,252,22,True,17.581161,35000000.0,17065924.0,17934076.0,3.216311e+14
112509,130278,98,3,0.000000,52.000000,4,False,False,76.000000,7490000.0,...,37.653103,3.00,22,6,True,2.352634,7490000.0,25317408.0,17827408.0,3.178165e+14
8231,8712,305,4,7.000000,45.000000,1,False,False,56.000000,35000000.0,...,37.565399,3.20,13,5,True,3.386857,35000000.0,17907078.0,17092922.0,2.921680e+14
115805,134008,2256,5,0.000000,73.300003,4,False,False,102.000000,38800000.0,...,37.524147,2.80,30,5,False,5.841884,38800000.0,21903296.0,16896704.0,2.854986e+14
102957,119004,2458,3,15.000000,35.000000,2,False,False,60.500000,2238000.0,...,37.632771,3.00,266,9,True,7.716379,2238000.0,18917952.0,16679952.0,2.782208e+14
98155,112896,24141,9,18.000000,42.000000,2,False,False,72.000000,39900000.0,...,37.635387,3.25,224,9,True,5.896209,39900000.0,23514966.0,16385034.0,2.684693e+14
44753,49025,7136,12,11.100000,45.700001,3,False,False,69.199997,19900000.0,...,37.586338,2.60,320,17,True,2.330916,19900000.0,36272608.0,16372608.0,2.680623e+14
40651,44505,3724,2,9.000000,63.000000,3,False,False,87.000000,20000000.0,...,37.608948,3.00,336,11,True,2.341760,20000000.0,35915504.0,15915504.0,2.533033e+14
93056,106434,17921,6,0.000000,0.000000,5,False,False,135.000000,22000000.0,...,37.569790,3.00,42,7,True,3.039084,22000000.0,37856924.0,15856924.0,2.514420e+14
59779,66990,1038,4,9.100000,33.200001,2,False,False,56.799999,39000000.0,...,37.606342,3.00,97,8,True,2.370503,39000000.0,23467632.0,15532368.0,2.412545e+14
17976,19596,24195,2,12.100000,19.799999,1,False,False,48.000000,32990000.0,...,37.564213,3.00,1630,44,True,3.935317,32990000.0,17701588.0,15288412.0,2.337355e+14